language: ruby
cache: bundler
before_install:
  - gem update --system 2.1.11
  - gem --version
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
  - gemfiles/rails-3.2.gemfile
  - gemfiles/rails-4.0.gemfile
  - gemfiles/rails-master.gemfile
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/rails-3.2.gemfile
